services:
  web:
    build: .
    command: "elixir --sname ${APP_NODE_NAME}@web --cookie ${APP_COOKIE} -S mix phx.server"
    user: "${HOST_UID}:${HOST_GID}"
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - mix_cache:/home/phoenix/.mix
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  livebook:
    image: ghcr.io/livebook-dev/livebook
    environment:
      - LIVEBOOK_COOKIE=${APP_COOKIE}
      - LIVEBOOK_DEFAULT_RUNTIME=attached:${APP_NODE_NAME}@web:${APP_COOKIE}
      - LIVEBOOK_HOME=/data/notebooks
      - LIVEBOOK_TOKEN_ENABLED=false
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./notebooks:/data/notebooks
volumes:
  pg_data:
  mix_cache:
